version: '3'
services:
  zookeeper:
    image: qnib/plain-zookeeper@sha256:6dfdaae24f3d1ef77e76dff85a5ab8ac7edb2d145935f213b7ae5176377eacc1
    ports:
      - "2181:2181"
  zkui:
    image: qnib/plain-zkui:8d3441d@sha256:d66972bd886ade9a8d7383f5064bd825f6d29275a282250cb0adf52475f67726
    ports:
      - "9090:9090"
  broker:
    image: qnib/plain-kafka:dirty
    ports:
      - "9092:9092"
      - "7071:7071"
    environment:
      KAFKA_BROKER_ID: '{{.Task.Slot}}'
      PROMETHEUS_ENABLE: 'true'
  prometheus:
    image: qnib/plain-prometheus:1.7.1
    ports:
      - "9091:9090"
  grafana:
    image: ${GRAFANA_IMG:-qnib/plain-grafana4:4.4.3}
    ports:
     - 3000:3000
    environment:
      - GRAFANA_DATA_SOURCES=prometheus
  exporter:
    image: ${EXPORTER_IMT:-qnib/plain-prometheus-exporter-kafka-zookeeper}
    ports:
      - "9381:9381"
